### ISSUE TITLE
detector orientation documentation

### ISSUE THREAD

**Issue by isaacmichaud** [jasonmhite/gefry3#3]
I can add `type = Point` to prevent the yaml deck to suppress the error from `problem.py`:

```    if assumed_default_detectors != []:
        ws = "Some detectors did not specify type, assuming point detector for: {}".format(assumed_default_detectors)
        warnings.warn(ws)
```
What are the other sensor type keywords?

**Comment by jasonmhite** [comment]
`Point` and `Oriented_Prism`, the second of which is available only if you have `pyst` installed.

Point detectors look like this:
```yaml
...
  - R: [7.8483202662318945, 70.70920296991244]
    type: Point
    name: D1
    area: 0.022367
    dwell: 1789.12521
    epsilon: 0.3 
...
```

Oriented detectors like this:
```yaml
...
  - R: [206.5165287629934, 79.54678464354947]
    name: D1
    type: Oriented_Prism
    lwh: [0.0508, 0.4064, 0.1016]
    theta: 0.44
    dwell: 1786.81359
    epsilon: 0.3 
...
```

`name` is optional in both cases and is currently ignored by the code, it's mostly there for organizing the input deck.

I hadn't documented the oriented detectors because I don't think anybody else is using them, but I can if you want to. I had to extend the syntax a bit to accommodate different types of detectors but I made it backwards compatible. If you use the old syntax (without the type specified) it assumes the detectors are point detectors, with the warning message provided just to be clear what it's doing.

If you wanna hide the warnings you can suppress the `UserWarning` type:

```python
import warnings

with warnings.catch_warnings():
    warnings.simplefilter("ignore", UserWarning)
    import gefry3
```
